# Generated by Django 6.0.1 on 2026-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='default_color',
            field=models.CharField(default='#8B4513', max_length=20),
        ),
    ]
