# Generated by Django 6.0.1 on 2026-01-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_color',
        ),
    ]
