# Generated by Django 6.0.1 on 2026-01-19 09:07

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=store.models.default_sizes),
        ),
    ]
