# Generated by Django 6.0.1 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_address_customer_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
