# Generated by Django 6.0.1 on 2026-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_security_answer_customer_security_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='security_question',
            field=models.CharField(blank=True, choices=[('website', 'Which is the website you frequently visit?'), ('school', 'What is the name of your first school?'), ('color', 'What is your favourite colour?'), ('vehicle', 'What is the registration number of your first vehicle?'), ('book', 'Which is your favourite book?'), ('sport', 'What is your favourite sport?'), ('birth', 'What is your place of birth?')], max_length=50, null=True),
        ),
    ]
